
<br /><br />
<div id="view-content">
  <p>View script for controller <b>Activity</b> and script/action name <b>index</b></p>
</div>



Our Activity Records: <br />

<?php
$columns = $this->retvalar['columns'];
$records = $this->retvalar['records'];
?>
<table>

  <tr>
    <?php foreach ($columns as $column): ?>
      <?php if ($this->escape($column) !== "id") { ?>
        <th><?php echo $this->escape($column); ?></th>
      <?php } ?>
    <?php endforeach; ?>
  </tr>

  <?php foreach ($records as $record): ?>
    <tr>
      <td><?php echo $this->escape($record->date) ?></td>
      <td><?php echo $this->escape($record->description) ?></td>
      <td><?php echo $this->escape($record->deposit) ?></td>
      <td><?php echo $this->escape($record->withdrawal) ?></td>
      <td><?php echo $this->escape($record->balance) ?></td>
    </tr>
  <?php endforeach ?>
</table>