
<br /><br />
<div id="view-content">
  <p>View script for controller <b>Activity</b> and script/action name <b>index</b></p>
</div>



Our Activity Records: <br />
<?php var_dump($this->records);?>
<ul>
  <?php foreach ($this->records as $record): ?>
  <li>
    <?php echo $this->escape($record->date) ?>
    <?php echo $this->escape($record->description) ?>
    <?php echo $this->escape($record->deposit) ?>
    <?php echo $this->escape($record->withrawal) ?>
    <?php echo $this->escape($record->balance) ?>
</li>
  <?php endforeach ?>
</ul>