
<br /><br />
<div id="view-content">
  <p>View script for controller <b>Activity</b> and script/action name <b>index</b></p>
</div>



Our Activity Records: <br />
<table>
  <?php foreach ($this->records as $record): ?>
    <tr>
      <td><?php echo $this->escape($record->date) ?></td>
      <td><?php echo $this->escape($record->description) ?></td>
      <td><?php echo $this->escape($record->deposit) ?></td>
      <td><?php echo $this->escape($record->withdrawal) ?></td>
      <td><?php echo $this->escape($record->balance) ?></td>
    </tr>
  <?php endforeach ?>
</table>