<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Bignay</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  </head>
  <body>
    <div id="header" style="background-color: #EEEEEE; height: 30px;">
      <div id="header-logo" style="float: left">
        <b>Bignay!</b>
      </div>
      <br/>
      <div id="header-navigation" style="float: left">
        <a href="<?php echo $this->url(array('controller' => 'activity'), 'default', true); ?>">Our activity</a>
      </div>
    </div>
    <div>
      <br/>
      <a href="/activity/date?dt=2000">For 2000</a> ::  
      <a href="/activity/date?dt=2009">For 2009</a> | 
      
      <a href="/activity/description?d=bought&c=withdrawal">"bought"</a> :: 
      <a href="/activity/description?d=gift&c=deposit">"gift"</a> |
    </div>
    <?php echo $this->layout()->content ?>
  </body>
</html>