<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Bignay</title>
    <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  </head>
  <body>
    <div id="header" style="background-color: #EEEEEE; height: 30px;">
      <div id="header-logo" style="float: left">
        <b>Bignay!</b>
      </div>
      <br/>
      <div id="header-navigation" style="float: left">
        <a href="<?php echo $this->url(array('controller' => 'activity'), 'default', true); ?>">Our activity</a>
      </div>
    </div>

    <?php 
    echo '<br>'. __LINE__;
    //echo '<pre>'; var_dump($this->layout()); echo '</pre>'; 
    var_dump($this->layout()->content );
      echo __LINE__;
      ?>
    

  </body>
</html>